webtalk_init -webtalk_dir D:/verilog_docs/HDMI_Demo/HDMI_Demo.sim/sim_1/behav/xsim/xsim.dir/TOP_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 31 23:58:41 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "38d6783c-1ae5-4163-ac2b-8daa9b71cccd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ca343cc225fa4eef8dfa41b7020fc365" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "23284684 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.53_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16120_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2460915935 -regid "" -xml D:/verilog_docs/HDMI_Demo/HDMI_Demo.sim/sim_1/behav/xsim/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/verilog_docs/HDMI_Demo/HDMI_Demo.sim/sim_1/behav/xsim/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/verilog_docs/HDMI_Demo/HDMI_Demo.sim/sim_1/behav/xsim/xsim.dir/TOP_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
