# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/verilog_docs/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Picture_G_Rom/Picture_G_Rom.xci
# IP: The module: 'Picture_G_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_docs/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Picture_G_Rom/Picture_G_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_G_Rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/verilog_docs/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Picture_G_Rom/Picture_G_Rom.xci
# IP: The module: 'Picture_G_Rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_docs/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/Picture_G_Rom/Picture_G_Rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Picture_G_Rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
